services:
  postgres:
    image: postgres:16
    container_name: platinum_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: platinum
    ports:
      - "5433:5432"
    volumes:
      - platinum_data:/var/lib/postgresql/data

volumes:
  platinum_data: